all: ringmaster player

ringmaster:
	g++ -Wall -Werror -std=gnu++11 -pedantic -ggdb3 ringmaster.cpp -o ringmaster

player:
	g++ -Wall -Werror -std=gnu++11 -pedantic -ggdb3 player.cpp -o player

clean:
	rm -f *~ *.o